`ifndef DPRAM_CONTROLLER_DEFINES_SV_
`define DPRAM_CONTROLLER_DEFINES_SV_

// Definiçao da maquina de estados de controle do Controller

typedef enum logic[2:0] {
	DPRAM_CONTROL_IDLE,
	DPRAM_CONTROL_READ_AB,
	DPRAM_CONTROL_ENABLE_MULT,
	DPRAM_CONTROL_WAIT_FOR_RESULT,
	DPRAM_CONTROL_STORE_Y,
	DPRAM_CONTROL_SIGNAL_STATUS_1,
	DPRAM_CONTROL_WAIT_FOR_CONTROL_CLEAR
} dpram_controller_state_e;

`define	DPRAM_CONTROL_ADDR	2'b00
`define	DPRAM_DATA_IN_ADDR	2'b01
`define	DPRAM_DATA_OUT_ADDR	2'b10
`define	DPRAM_STATUS_ADDR		2'b11

`endif // DPRAM_CONTROLLER_DEFINES_SV_
