`ifndef DPRAM_CONTROLLER_DEFINES_SV_
`define DPRAM_CONTROLLER_DEFINES_SV_

// Definiçao da maquina de estados de controle do Controller

typedef enum logic[2:0] {
	DPRAM_CONTROL_IDLE = 3'd0,
	DPRAM_CONTROL_READ_AB = 3'd1,
	DPRAM_CONTROL_ENABLE_MULT = 3'd2,
	DPRAM_CONTROL_WAIT_FOR_RESULT = 3'd3,
	DPRAM_CONTROL_STORE_Y = 3'd4,
	DPRAM_CONTROL_SIGNAL_STATUS_1 = 3'd5,
	DPRAM_CONTROL_WAIT_FOR_CONTROL_CLEAR = 3'd6
} dpram_controller_state_e;

`define	DPRAM_CONTROL_ADDR	2'b00
`define	DPRAM_DATA_IN_ADDR	2'b01
`define	DPRAM_DATA_OUT_ADDR	2'b10
`define	DPRAM_STATUS_ADDR		2'b11

`endif // DPRAM_CONTROLLER_DEFINES_SV_
